"""Change primary key of reposts to int

Revision ID: 008a220e1812
Revises: d711f13b2522
Create Date: 2023-07-07 11:36:25.521028

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '008a220e1812'
down_revision = 'd711f13b2522'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reason', sa.String(length=255), nullable=False))
        batch_op.alter_column('id',
               existing_type=mysql.VARCHAR(length=35),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.create_unique_constraint(None, ['reported_by'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=35),
               existing_nullable=False)
        batch_op.drop_column('reason')

    # ### end Alembic commands ###
