"""add disabled column to user

Revision ID: 2ee18ed77333
Revises: 008a220e1812
Create Date: 2023-07-08 09:32:35.398049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ee18ed77333'
down_revision = '008a220e1812'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('disabled', sa.Integer(), nullable=False))
        op.execute('UPDATE users SET disabled = 0;')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('disabled')

    # ### end Alembic commands ###
